import { useEffect, useMemo, useRef, useState } from 'react'
import { getApp, getApps, initializeApp } from 'firebase/app'
import { getDatabase, onValue, ref, set } from 'firebase/database'
import './Soil.css'

const firebaseConfig = {
  apiKey: 'AIzaSyB9ererNsNonAzH0zQo_GS79XPOyCoMxr4',
  authDomain: 'waterdtection.firebaseapp.com',
  databaseURL: 'https://waterdtection-default-rtdb.firebaseio.com',
  projectId: 'waterdtection',
  storageBucket: 'waterdtection.firebasestorage.app',
  messagingSenderId: '690886375729',
  appId: '1:690886375729:web:172c3a47dda6585e4e1810',
  measurementId: 'G-TXF33Y6XY0',
}

const firebaseApp = getApps().length ? getApp() : initializeApp(firebaseConfig)
const database = getDatabase(firebaseApp)

const DATABASE_PATH = 'Solar_Soil'
const HISTORY_LIMIT = 18
const PREFERRED_ORDER = [
  'Relay',
  'Soil',
  'Solar_Current',
  'Solar_Power',
  'Solar_Voltage',
]

const METRIC_META = {
  Relay: {
    label: 'PumpStatus',
    description: 'Pump controller state',
    kind: 'status',
  },
  Soil: {
    label: 'Soil',
    description: 'Soil reading',
    kind: 'numeric',
  },
  Solar_Current: {
    label: 'Solar Current',
    description: 'Current from solar input',
    kind: 'numeric',
    unit: 'mA',
    precision: 1,
    transform: (value) => value * 1000,
  },
  Solar_Power: {
    label: 'Solar Power',
    description: 'Power generated by panel',
    kind: 'numeric',
    unit: 'W',
    precision: 3,
  },
  Solar_Voltage: {
    label: 'Solar Voltage',
    description: 'Voltage from solar input',
    kind: 'numeric',
    unit: 'V',
    precision: 3,
  },
}

function toNumericValue(value) {
  if (typeof value === 'number') {
    return Number.isFinite(value) ? value : null
  }

  if (typeof value === 'string' && value.trim() !== '') {
    const parsed = Number(value)
    return Number.isFinite(parsed) ? parsed : null
  }

  return null
}

function formatMetricValue(metric, rawValue) {
  if (metric.kind === 'status') {
    return Number(rawValue) === 1 ? 'Pump On' : 'Pump Off'
  }

  const numericValue = toNumericValue(rawValue)

  if (numericValue === null) {
    return String(rawValue ?? '--')
  }

  const displayValue = metric.transform ? metric.transform(numericValue) : numericValue
  const precision = metric.precision ?? (Number.isInteger(displayValue) ? 0 : 2)
  return `${displayValue.toFixed(precision)}${metric.unit ? ` ${metric.unit}` : ''}`
}

function getMetricCode(metric) {
  if (metric.key === 'Relay') {
    return 'PM'
  }

  return metric.label
    .split(' ')
    .map((part) => part[0])
    .join('')
    .slice(0, 2)
    .toUpperCase()
}

function buildMetrics(data) {
  if (!data || typeof data !== 'object') {
    return []
  }

  const orderedKeys = [
    ...PREFERRED_ORDER.filter((key) => Object.hasOwn(data, key)),
    ...Object.keys(data)
      .filter((key) => !PREFERRED_ORDER.includes(key))
      .sort(),
  ]

  return orderedKeys.map((key) => ({
    key,
    rawValue: data[key],
    numericValue: toNumericValue(data[key]),
    ...(METRIC_META[key] ?? {
      label: key.replaceAll('_', ' '),
      description: 'Realtime sensor value',
      kind: 'numeric',
      precision: 2,
    }),
  }))
}

function formatUpdatedAt(timestamp) {
  if (!timestamp) {
    return 'Waiting for live updates'
  }

  return timestamp.toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
}

function getSoilAutomationState(soilValue) {
  if (soilValue === null) {
    return {
      label: 'No soil reading',
      relayValue: null,
      tone: 'idle',
      message: 'Waiting for a valid soil value before automatic control can respond.',
    }
  }

  if (soilValue <= 40) {
    return {
      label: 'Dry',
      relayValue: 1,
      tone: 'dry',
      message: 'Soil is dry. Pump turned on automatically.',
    }
  }

  return {
    label: 'Wet',
    relayValue: 0,
    tone: 'wet',
    message: 'Soil is above 40. Pump turned off automatically.',
  }
}

function MetricCard({ metric, index }) {
  return (
    <article className="metric-card">
      <div className="metric-card__header">
        <div className="metric-card__identity">
          <span className="metric-card__code">{getMetricCode(metric)}</span>
          <div>
            <p className="metric-card__eyebrow">Sensor {String(index + 1).padStart(2, '0')}</p>
            <p className="metric-card__title">{metric.label}</p>
          </div>
        </div>
        <span className="metric-card__type">
          {metric.kind === 'status' ? 'Controller' : 'Realtime'}
        </span>
      </div>
      <p className="metric-card__value">{formatMetricValue(metric, metric.rawValue)}</p>
      <div className="metric-card__footer">
        <p className="metric-card__description">{metric.description}</p>
      </div>
    </article>
  )
}

function ChartCard({ metric, points }) {
  const chartWidth = 320
  const chartHeight = 180
  const padding = 22
  const hasPoints = points.length > 0
  const values = points.map((point) => point.value)
  const actualMinValue = hasPoints ? Math.min(...values) : 0
  const actualMaxValue = hasPoints ? Math.max(...values) : 1
  const chartMinValue =
    metric.kind === 'status'
      ? 0
      : actualMinValue === actualMaxValue
        ? actualMinValue - Math.max(Math.abs(actualMinValue) * 0.15, 1)
        : actualMinValue
  const chartMaxValue =
    metric.kind === 'status'
      ? 1
      : actualMinValue === actualMaxValue
        ? actualMaxValue + Math.max(Math.abs(actualMaxValue) * 0.15, 1)
        : actualMaxValue
  const range = chartMaxValue - chartMinValue || 1

  const svgPoints = points.map((point, index) => {
    const x =
      points.length === 1
        ? chartWidth / 2
        : padding + (index / (points.length - 1)) * (chartWidth - padding * 2)

    const y =
      chartHeight -
      padding -
      ((point.value - chartMinValue) / range) * (chartHeight - padding * 2)

    return { x, y, ...point }
  })

  const linePath = svgPoints
    .map((point, index) => `${index === 0 ? 'M' : 'L'} ${point.x} ${point.y}`)
    .join(' ')

  const areaPath = svgPoints.length
    ? `${linePath} L ${svgPoints.at(-1).x} ${chartHeight - padding} L ${svgPoints[0].x} ${chartHeight - padding} Z`
    : ''

  const latestPoint = points.at(-1)
  const highestDisplayValue = metric.transform ? metric.transform(actualMaxValue) : actualMaxValue
  const lowestDisplayValue = metric.transform ? metric.transform(actualMinValue) : actualMinValue
  const highestLabel =
    metric.kind === 'status'
      ? 'Pump On'
      : `${highestDisplayValue.toFixed(metric.precision ?? 2)}${metric.unit ? ` ${metric.unit}` : ''}`
  const lowestLabel =
    metric.kind === 'status'
      ? 'Pump Off'
      : `${lowestDisplayValue.toFixed(metric.precision ?? 2)}${metric.unit ? ` ${metric.unit}` : ''}`

  return (
    <article className="chart-card">
      <div className="chart-card__header">
        <div>
          <p className="chart-card__eyebrow">{metric.label}</p>
          <h3>{formatMetricValue(metric, metric.rawValue)}</h3>
        </div>
        <div className="chart-card__legend">
          <span className="chart-card__metric-code">{getMetricCode(metric)}</span>
          <span>High: {highestLabel}</span>
          <span>Low: {lowestLabel}</span>
        </div>
      </div>

      <div className="chart-card__canvas">
        {hasPoints ? (
          <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} role="img" aria-label={`${metric.label} history graph`}>
            <defs>
              <linearGradient id={`fill-${metric.key}`} x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="rgba(15, 23, 42, 0.2)" />
                <stop offset="100%" stopColor="rgba(15, 23, 42, 0.02)" />
              </linearGradient>
            </defs>
            <line x1={padding} y1={padding} x2={padding} y2={chartHeight - padding} className="chart-grid" />
            <line
              x1={padding}
              y1={chartHeight - padding}
              x2={chartWidth - padding}
              y2={chartHeight - padding}
              className="chart-grid"
            />
            <path d={areaPath} fill={`url(#fill-${metric.key})`} />
            <path d={linePath} className="chart-line" />
            {svgPoints.map((point) => (
              <circle key={point.label} cx={point.x} cy={point.y} r="3.5" className="chart-point" />
            ))}
          </svg>
        ) : (
          <div className="chart-card__empty">
            <p>Waiting for chart data</p>
          </div>
        )}
      </div>

      <div className="chart-card__footer">
        <span>{points.length > 1 ? points[0].label : 'Just started'}</span>
        <span>{latestPoint?.label ?? 'No readings yet'}</span>
        <span>{points.length} samples</span>
      </div>
    </article>
  )
}

function Soil() {
  const [sensorData, setSensorData] = useState({})
  const [history, setHistory] = useState({})
  const [updatedAt, setUpdatedAt] = useState(null)
  const [status, setStatus] = useState('connecting')
  const [errorMessage, setErrorMessage] = useState('')
  const [controlMode, setControlMode] = useState('manual')
  const [controlNotice, setControlNotice] = useState({
    tone: 'idle',
    title: 'Manual control ready',
    message: 'Use the pump buttons below to change the relay value manually.',
  })
  const [isWritingRelay, setIsWritingRelay] = useState(false)
  const previousModeRef = useRef(controlMode)
  const modeSwitchingRef = useRef(false)

  useEffect(() => {
    const sensorRef = ref(database, DATABASE_PATH)

    const unsubscribe = onValue(
      sensorRef,
      (snapshot) => {
        const nextValue = snapshot.val()
        const safeData = nextValue && typeof nextValue === 'object' ? nextValue : {}
        const now = new Date()
        const label = now.toLocaleTimeString('en-IN', {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        })

        setSensorData(safeData)
        setUpdatedAt(now)
        setStatus('live')
        setErrorMessage('')
        setHistory((previousHistory) => {
          const nextHistory = { ...previousHistory }

          Object.entries(safeData).forEach(([key, value]) => {
            const numericValue = toNumericValue(value)

            if (numericValue === null) {
              return
            }

            const previousPoints = previousHistory[key] ?? []
            const lastPoint = previousPoints.at(-1)

            if (lastPoint?.value === numericValue) {
              nextHistory[key] = previousPoints
              return
            }

            nextHistory[key] = [...previousPoints, { label, value: numericValue }].slice(
              -HISTORY_LIMIT,
            )
          })

          return nextHistory
        })
      },
      (error) => {
        setStatus('error')
        setErrorMessage(error.message)
      },
    )

    return () => unsubscribe()
  }, [])

  const metrics = useMemo(() => buildMetrics(sensorData), [sensorData])
  const pumpMetric = metrics.find((metric) => metric.key === 'Relay')
  const isPumpOn = Number(pumpMetric?.rawValue) === 1
  const soilValue = toNumericValue(sensorData.Soil)
  const soilAutomation = useMemo(() => getSoilAutomationState(soilValue), [soilValue])

  useEffect(() => {
    if (previousModeRef.current === controlMode) {
      return
    }

    const previousMode = previousModeRef.current
    previousModeRef.current = controlMode
    modeSwitchingRef.current = true

    let isCancelled = false

    async function resetRelayForModeSwitch() {
      setIsWritingRelay(true)
      setControlNotice({
        tone: 'idle',
        title: 'Switching control mode',
        message: `Changed from ${previousMode} to ${controlMode}. Relay is resetting to 0 before the new mode takes over.`,
      })

      try {
        await set(ref(database, `${DATABASE_PATH}/Relay`), 0)

        if (isCancelled) {
          return
        }

        setControlNotice({
          tone: 'idle',
          title: controlMode === 'manual' ? 'Manual mode active' : 'Automatic mode active',
          message:
            controlMode === 'manual'
              ? 'Relay was reset to 0. Use the manual buttons to control the pump.'
              : 'Relay was reset to 0. Automatic soil rules are ready to manage the pump.',
        })
      } catch (error) {
        if (isCancelled) {
          return
        }

        setControlNotice({
          tone: 'error',
          title: 'Mode switch reset failed',
          message: error.message,
        })
      } finally {
        if (!isCancelled) {
          setIsWritingRelay(false)
          modeSwitchingRef.current = false
        }
      }
    }

    resetRelayForModeSwitch()

    return () => {
      isCancelled = true
    }
  }, [controlMode])

  useEffect(() => {
    if (controlMode !== 'manual' || modeSwitchingRef.current) {
      return
    }

    setControlNotice({
      tone: 'idle',
      title: 'Manual control active',
      message: 'Pump on and pump off will only update the Relay value in Firebase.',
    })
  }, [controlMode])

  useEffect(() => {
    if (controlMode !== 'auto' || modeSwitchingRef.current) {
      return
    }

    setControlNotice({
      tone: soilAutomation.tone,
      title: `Automatic mode: ${soilAutomation.label}`,
      message: soilAutomation.message,
    })

    if (isWritingRelay) {
      return
    }

    if (soilAutomation.relayValue === null) {
      return
    }

    const currentRelayValue = toNumericValue(sensorData.Relay)

    if (currentRelayValue === soilAutomation.relayValue) {
      return
    }

    let isCancelled = false

    async function applyAutoRelay() {
      setIsWritingRelay(true)

      try {
        await set(ref(database, `${DATABASE_PATH}/Relay`), soilAutomation.relayValue)

        if (isCancelled) {
          return
        }

        setControlNotice({
          tone: soilAutomation.tone,
          title: `Automatic mode: ${soilAutomation.label}`,
          message: soilAutomation.message,
        })
      } catch (error) {
        if (isCancelled) {
          return
        }

        setControlNotice({
          tone: 'error',
          title: 'Automatic update failed',
          message: error.message,
        })
      } finally {
        setIsWritingRelay(false)
      }
    }

    applyAutoRelay()

    return () => {
      isCancelled = true
    }
  }, [controlMode, isWritingRelay, sensorData.Relay, soilAutomation])

  async function updateRelayManually(nextRelayValue) {
    setIsWritingRelay(true)

    try {
      await set(ref(database, `${DATABASE_PATH}/Relay`), nextRelayValue)
      setControlNotice({
        tone: nextRelayValue === 1 ? 'dry' : 'normal',
        title: 'Manual relay updated',
        message:
          nextRelayValue === 1
            ? 'Pump turned on manually by updating the Relay value.'
            : 'Pump turned off manually by updating the Relay value.',
      })
    } catch (error) {
      setControlNotice({
        tone: 'error',
        title: 'Manual update failed',
        message: error.message,
      })
    } finally {
      setIsWritingRelay(false)
    }
  }

  return (
    <main className="soil-page">
      <section className="topbar">
        <div className="topbar__brand">
          <span className="topbar__brand-mark">WS</span>
          <div>
            <p className="topbar__label">Water Detection</p>
            <h1 className="topbar__title">Solar Soil Command Board</h1>
          </div>
        </div>

        <div className="topbar__status">
          <div className={`status-chip status-chip--${status}`}>
            <span className="status-chip__dot" aria-hidden="true"></span>
            {status === 'live' ? 'Live connection' : status === 'error' ? 'Connection error' : 'Connecting'}
          </div>
        </div>
      </section>

      <section className="hero-panel">
        <div className="hero-panel__content">
          <p className="hero-panel__eyebrow">Realtime Firebase Dashboard</p>
          <h2>Track solar power, voltage, current, soil state, and pump control in one place.</h2>
          <p className="hero-panel__copy">
            Live data is being read from <code>{DATABASE_PATH}</code>, with Relay renamed as
            <strong> PumpStatus</strong> on the frontend.
          </p>

          <div className="hero-panel__facts">
            <div className="meta-card">
              <span>Database Path</span>
              <strong>{DATABASE_PATH}</strong>
            </div>
            <div className="meta-card">
              <span>Last Update</span>
              <strong>{formatUpdatedAt(updatedAt)}</strong>
            </div>
            <div className="meta-card">
              <span>Tracked Metrics</span>
              <strong>{metrics.length || 0}</strong>
            </div>
          </div>
        </div>

        <div className={`spotlight-card ${isPumpOn ? 'spotlight-card-on' : ''}`}>
          <p className="spotlight-card__eyebrow">Primary Control</p>
          <div className="spotlight-card__orb">
            <span className="spotlight-card__ring"></span>
            <strong>{isPumpOn ? 'ON' : 'OFF'}</strong>
          </div>
          <h3>PumpStatus</h3>
          <p>{isPumpOn ? 'Water pump is actively running.' : 'Water pump is currently stopped.'}</p>
          <div className="spotlight-card__pill-row">
            <span className="spotlight-pill">Relay: {pumpMetric?.rawValue ?? '--'}</span>
            <span className="spotlight-pill">{status === 'live' ? 'Synced' : 'Waiting'}</span>
          </div>
        </div>
      </section>

      {errorMessage ? <p className="banner-error">{errorMessage}</p> : null}

      <section className="section-block">
        <div className="section-heading">
          <div>
            <p className="section-label">Pump Control</p>
            <h3>Manual and automatic control</h3>
          </div>
        </div>

        <div className="control-grid">
          <article className="control-card">
            <div className="control-card__header">
              <div>
                <p className="section-label">Mode Select</p>
                <h4>Choose how the pump is controlled</h4>
              </div>
              <div className="control-toggle" role="tablist" aria-label="Pump control mode">
                <button
                  type="button"
                  className={controlMode === 'manual' ? 'control-toggle__button active' : 'control-toggle__button'}
                  onClick={() => setControlMode('manual')}
                >
                  Manual
                </button>
                <button
                  type="button"
                  className={controlMode === 'auto' ? 'control-toggle__button active' : 'control-toggle__button'}
                  onClick={() => setControlMode('auto')}
                >
                  Automatic
                </button>
              </div>
            </div>

            <div className="control-mode-panels">
              <div className={`mode-panel ${controlMode === 'manual' ? 'mode-panel-active' : ''}`}>
                <p className="section-label">Manual Section</p>
                <h5>Relay-based pump switching</h5>
                <p>
                  In manual mode, only the <code>Relay</code> value is updated when the user turns
                  the pump on or off.
                </p>
                <div className="manual-actions">
                  <button
                    type="button"
                    className="action-button action-button-on"
                    onClick={() => updateRelayManually(1)}
                    disabled={controlMode !== 'manual' || isWritingRelay}
                  >
                    Pump On
                  </button>
                  <button
                    type="button"
                    className="action-button action-button-off"
                    onClick={() => updateRelayManually(0)}
                    disabled={controlMode !== 'manual' || isWritingRelay}
                  >
                    Pump Off
                  </button>
                </div>
              </div>

              <div className={`mode-panel ${controlMode === 'auto' ? 'mode-panel-active' : ''}`}>
                <p className="section-label">Automatic Section</p>
                <h5>Soil-based smart control</h5>
                <p>Automatic mode checks soil and controls the relay using these rules.</p>
                <div className="rule-list">
                  <span className="rule-pill">0 to 40: Dry, pump on</span>
                  <span className="rule-pill">Above 40: Wet, pump off</span>
                </div>
              </div>
            </div>
          </article>

          <article className={`alert-card alert-card--${controlNotice.tone}`}>
            <p className="section-label">React Alert</p>
            <h4>{controlNotice.title}</h4>
            <p>{controlNotice.message}</p>
            <div className="alert-card__meta">
              <span>Current soil: {soilValue ?? '--'}</span>
              <span>Current relay: {sensorData.Relay ?? '--'}</span>
              <span>{isWritingRelay ? 'Updating Relay...' : 'Relay synced'}</span>
            </div>
          </article>
        </div>
      </section>

      <section className="section-block">
        <div className="section-heading">
          <div>
            <p className="section-label">Live Values</p>
            <h3>Individual sensor cards</h3>
          </div>
        </div>

        <div className="metrics-grid">
          {metrics.length ? (
            metrics.map((metric, index) => <MetricCard key={metric.key} metric={metric} index={index} />)
          ) : (
            <article className="empty-card">
              <p>No sensor values found yet at the Firebase path.</p>
            </article>
          )}
        </div>
      </section>

      <section className="section-block">
        <div className="section-heading">
          <div>
            <p className="section-label">Separate Graphs</p>
            <h3>Realtime history for every metric</h3>
          </div>
        </div>

        <div className="charts-grid">
          {metrics.map((metric) => (
            <ChartCard key={metric.key} metric={metric} points={history[metric.key] ?? []} />
          ))}
        </div>
      </section>
    </main>
  )
}

export default Soil
